### ISSUE TITLE
FuseSDKiOS 2.2.0 crashes durring app startup on iOS7

### ISSUE THREAD

**Issue by aksyr** [fusepowered/FuseSDKiOS#19]
FuseSDKiOS 2.2.0 crashes durring app startup on iOS7. Everything works fine when using 2.1.4.

Console output:
> dyld: Symbol not found: _SKStoreProductParameterAffiliateToken
>  Referenced from: /var/mobile/Applications/<id>/<name>.app/<name>
>  Expected in: /System/Library/Frameworks/StoreKit.framework/StoreKit
> in /var/mobile/Applications/<id>/<name>.app/<name>

**Comment by akokulu** [comment]
Hi there,
Can you please make sure the frameworks in this link are included?
https://wiki.fusepowered.com/index.php?title=IOS#Required_Frameworks
